name: Bot Cryptone 24/7

concurrency:
  group: bot-cryptone
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 355
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ← INI YG DITAMBAHIN
      
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
